[2025-05-31T11:26:35.666-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-31T11:26:35.714-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [queued]>
[2025-05-31T11:26:35.733-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [queued]>
[2025-05-31T11:26:35.733-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-31T11:26:35.755-0600] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): classify_modems> on 2025-05-30 10:00:00+00:00
[2025-05-31T11:26:35.768-0600] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2742) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-31T11:26:35.771-0600] {standard_task_runner.py:72} INFO - Started process 2744 to run task
[2025-05-31T11:26:35.772-0600] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'libertyPr_health_score_1', 'classify_modems', 'scheduled__2025-05-30T10:00:00+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/health_score_lpr.py', '--cfg-path', '/tmp/tmpapqrp48q']
[2025-05-31T11:26:35.777-0600] {standard_task_runner.py:105} INFO - Job 210: Subtask classify_modems
[2025-05-31T11:26:35.876-0600] {task_command.py:467} INFO - Running <TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [running]> on host 439130e6349d
[2025-05-31T11:26:36.064-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='libertyPr_health_score_1' AIRFLOW_CTX_TASK_ID='classify_modems' AIRFLOW_CTX_EXECUTION_DATE='2025-05-30T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-30T10:00:00+00:00'
[2025-05-31T11:26:36.065-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-31T11:26:36.092-0600] {logging_mixin.py:190} INFO - üì• Loading modem and status data...
[2025-05-31T11:26:41.867-0600] {logging_mixin.py:190} INFO - ‚úÖ Loaded modem data: 1773815 rows from /tmp/modem_data.csv
[2025-05-31T11:26:41.867-0600] {logging_mixin.py:190} INFO - ‚úÖ Loaded status data: 477206 rows from /tmp/modem_status.csv
[2025-05-31T11:26:42.357-0600] {logging_mixin.py:190} INFO - üìä Unique CM_MACs in modem_df: 476424
[2025-05-31T11:26:42.493-0600] {logging_mixin.py:190} INFO - üìä Unique CM_MACs in status_df: 476652
[2025-05-31T11:26:42.494-0600] {logging_mixin.py:190} INFO - üßÆ Classifying each channel...
[2025-05-31T11:27:27.278-0600] {logging_mixin.py:190} INFO - ‚úÖ Channel classification complete.
[2025-05-31T11:27:27.360-0600] {logging_mixin.py:190} INFO -          CM_MAC       PTIME Channel_Status
0  400D102E5E03  2025-05-29        Warning
1  1835D1E0BD93  2025-05-29           Good
2  400D102E5E03  2025-05-29        Warning
3  400D102E5E03  2025-05-29        Warning
4  1835D1E0BD93  2025-05-29           Good
[2025-05-31T11:27:27.385-0600] {logging_mixin.py:190} INFO - üìä Grouping and summarizing modem data...
[2025-05-31T11:37:05.046-0600] {logging_mixin.py:190} INFO - ‚úÖ Grouped modem data shape: (476424, 4)
[2025-05-31T11:37:05.131-0600] {logging_mixin.py:190} INFO - ‚úÖ Summarized modem data (head):
[2025-05-31T11:37:05.152-0600] {logging_mixin.py:190} INFO -          CM_MAC       PTIME  ...              CHANNEL_NAME TX_MAX
0  00015C6CD846  2025-05-29  ...  cable-upstream 3/10/12.0    NaN
1  00071100F727  2025-05-29  ...    cable-upstream 2/6/7.0    NaN
2  00071117BB9F  2025-05-29  ...   cable-upstream 2/1/13.0    NaN
3  00071117BBAE  2025-05-29  ...    cable-upstream 2/9/2.0    NaN
4  00071117BC0D  2025-05-29  ...    cable-upstream 2/9/2.0    NaN

[5 rows x 6 columns]
[2025-05-31T11:37:05.153-0600] {logging_mixin.py:190} INFO - üîó Merging modem-level data with status (LEFT join)...
[2025-05-31T11:37:06.426-0600] {logging_mixin.py:190} INFO - ‚úÖ Merged dataset shape: (476488, 19)
[2025-05-31T11:37:06.427-0600] {logging_mixin.py:190} INFO - üìä Rows with no ONLINE_COUNT after merge: 0
[2025-05-31T11:37:06.428-0600] {logging_mixin.py:190} INFO - üõ† Applying final classification rules...
[2025-05-31T11:37:06.485-0600] {logging_mixin.py:190} INFO - üìä Classification summary after status logic:
[2025-05-31T11:37:06.494-0600] {logging_mixin.py:190} INFO - Category
Good        246228
Warning     136216
Critical     88157
Offline       5887
Name: count, dtype: int64
[2025-05-31T11:37:11.273-0600] {logging_mixin.py:190} INFO - üíæ Saved classified modems to /tmp/classified_modems.csv
[2025-05-31T11:37:11.274-0600] {logging_mixin.py:190} INFO - üîç Final modem count: 476488 rows
[2025-05-31T11:37:11.608-0600] {python.py:240} INFO - Done. Returned value was: None
[2025-05-31T11:37:11.630-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-31T11:37:11.631-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=libertyPr_health_score_1, task_id=classify_modems, run_id=scheduled__2025-05-30T10:00:00+00:00, execution_date=20250530T100000, start_date=20250531T172635, end_date=20250531T173711
[2025-05-31T11:37:11.779-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-31T11:37:11.827-0600] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-31T11:37:11.830-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-31T14:02:23.222-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-31T14:02:23.266-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [queued]>
[2025-05-31T14:02:23.281-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [queued]>
[2025-05-31T14:02:23.282-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-31T14:02:23.304-0600] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): classify_modems> on 2025-05-30 10:00:00+00:00
[2025-05-31T14:02:23.316-0600] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4670) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-31T14:02:23.319-0600] {standard_task_runner.py:72} INFO - Started process 4672 to run task
[2025-05-31T14:02:23.320-0600] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'libertyPr_health_score_1', 'classify_modems', 'scheduled__2025-05-30T10:00:00+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/health_score_lpr.py', '--cfg-path', '/tmp/tmpnqsimzix']
[2025-05-31T14:02:23.324-0600] {standard_task_runner.py:105} INFO - Job 220: Subtask classify_modems
[2025-05-31T14:02:23.423-0600] {task_command.py:467} INFO - Running <TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [running]> on host 439130e6349d
[2025-05-31T14:02:23.566-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='libertyPr_health_score_1' AIRFLOW_CTX_TASK_ID='classify_modems' AIRFLOW_CTX_EXECUTION_DATE='2025-05-30T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-30T10:00:00+00:00'
[2025-05-31T14:02:23.568-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-31T14:02:23.597-0600] {logging_mixin.py:190} INFO - üì• Loading modem and status data...
[2025-05-31T14:02:29.313-0600] {logging_mixin.py:190} INFO - ‚úÖ Loaded modem data: 1773815 rows from /tmp/modem_data.csv
[2025-05-31T14:02:29.314-0600] {logging_mixin.py:190} INFO - ‚úÖ Loaded status data: 477206 rows from /tmp/modem_status.csv
[2025-05-31T14:02:29.875-0600] {logging_mixin.py:190} INFO - üìä Unique CM_MACs in modem_df: 476424
[2025-05-31T14:02:30.015-0600] {logging_mixin.py:190} INFO - üìä Unique CM_MACs in status_df: 476652
[2025-05-31T14:02:30.015-0600] {logging_mixin.py:190} INFO - üßÆ Classifying each channel...
[2025-05-31T14:03:14.783-0600] {logging_mixin.py:190} INFO - ‚úÖ Channel classification complete.
[2025-05-31T14:03:14.861-0600] {logging_mixin.py:190} INFO -          CM_MAC       PTIME Channel_Status
0  1835D1B73F73  2025-05-29           Good
1  50A5DC21FB37  2025-05-29           Good
2  50A5DC21FB37  2025-05-29           Good
3  50A5DC21FB37  2025-05-29           Good
4  50A5DC21FB37  2025-05-29           Good
[2025-05-31T14:03:14.884-0600] {logging_mixin.py:190} INFO - üìä Grouping and summarizing modem data...
[2025-05-31T14:13:04.911-0600] {logging_mixin.py:190} INFO - ‚úÖ Grouped modem data shape: (476424, 4)
[2025-05-31T14:13:04.999-0600] {logging_mixin.py:190} INFO - ‚úÖ Summarized modem data (head):
[2025-05-31T14:13:05.022-0600] {logging_mixin.py:190} INFO -          CM_MAC       PTIME  ...              CHANNEL_NAME TX_MAX
0  00015C6CD846  2025-05-29  ...  cable-upstream 3/10/12.0    NaN
1  00071100F727  2025-05-29  ...    cable-upstream 2/6/7.0    NaN
2  00071117BB9F  2025-05-29  ...   cable-upstream 2/1/13.0    NaN
3  00071117BBAE  2025-05-29  ...    cable-upstream 2/9/2.0    NaN
4  00071117BC0D  2025-05-29  ...    cable-upstream 2/9/2.0    NaN

[5 rows x 6 columns]
[2025-05-31T14:13:05.023-0600] {logging_mixin.py:190} INFO - üîó Merging modem-level data with status (LEFT join)...
[2025-05-31T14:13:06.410-0600] {logging_mixin.py:190} INFO - ‚úÖ Merged dataset shape: (476488, 19)
[2025-05-31T14:13:06.412-0600] {logging_mixin.py:190} INFO - üìä Rows with no ONLINE_COUNT after merge: 0
[2025-05-31T14:13:06.413-0600] {logging_mixin.py:190} INFO - üõ† Applying final classification rules...
[2025-05-31T14:13:06.477-0600] {logging_mixin.py:190} INFO - üìä Classification summary after status logic:
[2025-05-31T14:13:06.488-0600] {logging_mixin.py:190} INFO - Category
Good        246228
Warning     136216
Critical     88157
Offline       5887
Name: count, dtype: int64
[2025-05-31T14:13:11.812-0600] {logging_mixin.py:190} INFO - üíæ Saved classified modems to /tmp/classified_modems.csv
[2025-05-31T14:13:11.813-0600] {logging_mixin.py:190} INFO - üîç Final modem count: 476488 rows
[2025-05-31T14:13:12.143-0600] {python.py:240} INFO - Done. Returned value was: None
[2025-05-31T14:13:12.179-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-31T14:13:12.179-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=libertyPr_health_score_1, task_id=classify_modems, run_id=scheduled__2025-05-30T10:00:00+00:00, execution_date=20250530T100000, start_date=20250531T200223, end_date=20250531T201312
[2025-05-31T14:13:12.304-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-31T14:13:12.350-0600] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-31T14:13:12.353-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-31T14:36:04.577-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-31T14:36:04.615-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [queued]>
[2025-05-31T14:36:04.628-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [queued]>
[2025-05-31T14:36:04.629-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-31T14:36:04.646-0600] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): classify_modems> on 2025-05-30 10:00:00+00:00
[2025-05-31T14:36:04.657-0600] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5100) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-31T14:36:04.660-0600] {standard_task_runner.py:72} INFO - Started process 5102 to run task
[2025-05-31T14:36:04.661-0600] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'libertyPr_health_score_1', 'classify_modems', 'scheduled__2025-05-30T10:00:00+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/health_score_lpr.py', '--cfg-path', '/tmp/tmpb3ql7c8l']
[2025-05-31T14:36:04.665-0600] {standard_task_runner.py:105} INFO - Job 227: Subtask classify_modems
[2025-05-31T14:36:04.762-0600] {task_command.py:467} INFO - Running <TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [running]> on host 439130e6349d
[2025-05-31T14:36:04.896-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='libertyPr_health_score_1' AIRFLOW_CTX_TASK_ID='classify_modems' AIRFLOW_CTX_EXECUTION_DATE='2025-05-30T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-30T10:00:00+00:00'
[2025-05-31T14:36:04.898-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-31T14:36:04.923-0600] {logging_mixin.py:190} INFO - üì• Loading modem and status data...
[2025-05-31T14:36:10.592-0600] {logging_mixin.py:190} INFO - ‚úÖ Loaded modem data: 1770208 rows from /tmp/modem_data.csv
[2025-05-31T14:36:10.593-0600] {logging_mixin.py:190} INFO - ‚úÖ Loaded status data: 477080 rows from /tmp/modem_status.csv
[2025-05-31T14:36:11.277-0600] {logging_mixin.py:190} INFO - üìä Unique CM_MACs in modem_df: 476288
[2025-05-31T14:36:11.424-0600] {logging_mixin.py:190} INFO - üìä Unique CM_MACs in status_df: 476505
[2025-05-31T14:36:11.425-0600] {logging_mixin.py:190} INFO - üßÆ Classifying each channel...
[2025-05-31T14:36:59.274-0600] {logging_mixin.py:190} INFO - ‚úÖ Channel classification complete.
[2025-05-31T14:36:59.352-0600] {logging_mixin.py:190} INFO -          CM_MAC       PTIME Channel_Status
0  ACF8CC3A9185  2025-05-30           Good
1  ACF8CC16E09B  2025-05-30           Good
2  E45740B88160  2025-05-30           Good
3  400D102C93C3  2025-05-30           Good
4  B05DD446D10D  2025-05-30           Good
[2025-05-31T14:36:59.375-0600] {logging_mixin.py:190} INFO - üìä Grouping and summarizing modem data...
[2025-05-31T14:46:31.881-0600] {logging_mixin.py:190} INFO - ‚úÖ Grouped modem data shape: (476288, 4)
[2025-05-31T14:46:31.981-0600] {logging_mixin.py:190} INFO - ‚úÖ Summarized modem data (head):
[2025-05-31T14:46:32.018-0600] {logging_mixin.py:190} INFO -          CM_MAC       PTIME  ...              CHANNEL_NAME TX_MAX
0  00015C6CD846  2025-05-30  ...  cable-upstream 3/10/12.0    NaN
1  00071100F727  2025-05-30  ...    cable-upstream 2/6/7.0    NaN
2  000711146ABC  2025-05-30  ...   cable-upstream 4/7/14.0    NaN
3  00071117BB95  2025-05-30  ...    cable-upstream 4/4/0.0    NaN
4  00071117BBAE  2025-05-30  ...    cable-upstream 2/9/2.0    NaN

[5 rows x 6 columns]
[2025-05-31T14:46:32.019-0600] {logging_mixin.py:190} INFO - üîó Merging modem-level data with status (LEFT join)...
[2025-05-31T14:46:33.328-0600] {logging_mixin.py:190} INFO - ‚úÖ Merged dataset shape: (476363, 19)
[2025-05-31T14:46:33.330-0600] {logging_mixin.py:190} INFO - üìä Rows with no ONLINE_COUNT after merge: 0
[2025-05-31T14:46:33.330-0600] {logging_mixin.py:190} INFO - üõ† Applying final classification rules...
[2025-05-31T14:46:33.380-0600] {logging_mixin.py:190} INFO - üìä Classification summary after status logic:
[2025-05-31T14:46:33.388-0600] {logging_mixin.py:190} INFO - Category
Good        238617
Warning     138159
Critical     93506
Offline       6081
Name: count, dtype: int64
[2025-05-31T14:46:38.167-0600] {logging_mixin.py:190} INFO - üíæ Saved classified modems to /tmp/classified_modems.csv
[2025-05-31T14:46:38.168-0600] {logging_mixin.py:190} INFO - üîç Final modem count: 476363 rows
[2025-05-31T14:46:38.452-0600] {python.py:240} INFO - Done. Returned value was: None
[2025-05-31T14:46:38.473-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-31T14:46:38.474-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=libertyPr_health_score_1, task_id=classify_modems, run_id=scheduled__2025-05-30T10:00:00+00:00, execution_date=20250530T100000, start_date=20250531T203604, end_date=20250531T204638
[2025-05-31T14:46:38.618-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-31T14:46:38.691-0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-31T14:46:38.696-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-31T15:19:50.573-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-31T15:19:50.617-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [queued]>
[2025-05-31T15:19:50.634-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [queued]>
[2025-05-31T15:19:50.635-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-31T15:19:50.655-0600] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): classify_modems> on 2025-05-30 10:00:00+00:00
[2025-05-31T15:19:50.666-0600] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5678) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-31T15:19:50.669-0600] {standard_task_runner.py:72} INFO - Started process 5680 to run task
[2025-05-31T15:19:50.670-0600] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'libertyPr_health_score_1', 'classify_modems', 'scheduled__2025-05-30T10:00:00+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/health_score_lpr.py', '--cfg-path', '/tmp/tmp78c0or_s']
[2025-05-31T15:19:50.675-0600] {standard_task_runner.py:105} INFO - Job 241: Subtask classify_modems
[2025-05-31T15:19:50.753-0600] {task_command.py:467} INFO - Running <TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [running]> on host 439130e6349d
[2025-05-31T15:19:50.896-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='libertyPr_health_score_1' AIRFLOW_CTX_TASK_ID='classify_modems' AIRFLOW_CTX_EXECUTION_DATE='2025-05-30T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-30T10:00:00+00:00'
[2025-05-31T15:19:50.900-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-31T15:19:50.924-0600] {logging_mixin.py:190} INFO - üì• Loading modem and status data...
[2025-05-31T15:19:56.683-0600] {logging_mixin.py:190} INFO - ‚úÖ Loaded modem data: 1770208 rows from /tmp/modem_data.csv
[2025-05-31T15:19:56.683-0600] {logging_mixin.py:190} INFO - ‚úÖ Loaded status data: 477080 rows from /tmp/modem_status.csv
[2025-05-31T15:19:57.186-0600] {logging_mixin.py:190} INFO - üìä Unique CM_MACs in modem_df: 476288
[2025-05-31T15:19:57.314-0600] {logging_mixin.py:190} INFO - üìä Unique CM_MACs in status_df: 476505
[2025-05-31T15:19:57.315-0600] {logging_mixin.py:190} INFO - üßÆ Classifying each channel...
[2025-05-31T15:20:43.074-0600] {logging_mixin.py:190} INFO - ‚úÖ Channel classification complete.
[2025-05-31T15:20:43.153-0600] {logging_mixin.py:190} INFO -          CM_MAC       PTIME Channel_Status
0  B05DD4437F3A  2025-05-30           Good
1  B05DD4437F3A  2025-05-30           Good
2  B05DD4437F3A  2025-05-30           Good
3  80CC9CB36C48  2025-05-30           Good
4  50A5DC6AADDC  2025-05-30           Good
[2025-05-31T15:20:43.176-0600] {logging_mixin.py:190} INFO - üìä Grouping and summarizing modem data...
[2025-05-31T15:30:28.685-0600] {logging_mixin.py:190} INFO - ‚úÖ Grouped modem data shape: (476288, 4)
[2025-05-31T15:30:28.777-0600] {logging_mixin.py:190} INFO - ‚úÖ Summarized modem data (head):
[2025-05-31T15:30:28.798-0600] {logging_mixin.py:190} INFO -          CM_MAC       PTIME  ...              CHANNEL_NAME TX_MAX
0  00015C6CD846  2025-05-30  ...  cable-upstream 3/10/12.0    NaN
1  00071100F727  2025-05-30  ...    cable-upstream 2/6/7.0    NaN
2  000711146ABC  2025-05-30  ...   cable-upstream 4/7/14.0    NaN
3  00071117BB95  2025-05-30  ...    cable-upstream 4/4/0.0    NaN
4  00071117BBAE  2025-05-30  ...    cable-upstream 2/9/2.0    NaN

[5 rows x 6 columns]
[2025-05-31T15:30:28.798-0600] {logging_mixin.py:190} INFO - üîó Merging modem-level data with status (LEFT join)...
[2025-05-31T15:30:30.174-0600] {logging_mixin.py:190} INFO - ‚úÖ Merged dataset shape: (476363, 19)
[2025-05-31T15:30:30.176-0600] {logging_mixin.py:190} INFO - üìä Rows with no ONLINE_COUNT after merge: 0
[2025-05-31T15:30:30.176-0600] {logging_mixin.py:190} INFO - üõ† Applying final classification rules...
[2025-05-31T15:30:30.228-0600] {logging_mixin.py:190} INFO - üìä Classification summary after status logic:
[2025-05-31T15:30:30.238-0600] {logging_mixin.py:190} INFO - Category
Good        238617
Warning     138159
Critical     93506
Offline       6081
Name: count, dtype: int64
[2025-05-31T15:30:35.274-0600] {logging_mixin.py:190} INFO - üíæ Saved classified modems to /tmp/classified_modems.csv
[2025-05-31T15:30:35.274-0600] {logging_mixin.py:190} INFO - üîç Final modem count: 476363 rows
[2025-05-31T15:30:35.584-0600] {python.py:240} INFO - Done. Returned value was: None
[2025-05-31T15:30:35.602-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-31T15:30:35.603-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=libertyPr_health_score_1, task_id=classify_modems, run_id=scheduled__2025-05-30T10:00:00+00:00, execution_date=20250530T100000, start_date=20250531T211950, end_date=20250531T213035
[2025-05-31T15:30:35.730-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-31T15:30:35.770-0600] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-31T15:30:35.771-0600] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-05-31T15:30:35.772-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-31T16:44:40.887-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-31T16:44:40.929-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [queued]>
[2025-05-31T16:44:40.950-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [queued]>
[2025-05-31T16:44:40.951-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-31T16:44:40.978-0600] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): classify_modems> on 2025-05-30 10:00:00+00:00
[2025-05-31T16:44:40.992-0600] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=6766) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-31T16:44:40.994-0600] {standard_task_runner.py:72} INFO - Started process 6768 to run task
[2025-05-31T16:44:40.995-0600] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'libertyPr_health_score_1', 'classify_modems', 'scheduled__2025-05-30T10:00:00+00:00', '--job-id', '258', '--raw', '--subdir', 'DAGS_FOLDER/health_score_lpr.py', '--cfg-path', '/tmp/tmpig1fetiq']
[2025-05-31T16:44:40.999-0600] {standard_task_runner.py:105} INFO - Job 258: Subtask classify_modems
[2025-05-31T16:44:41.090-0600] {task_command.py:467} INFO - Running <TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [running]> on host 439130e6349d
[2025-05-31T16:44:41.248-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='libertyPr_health_score_1' AIRFLOW_CTX_TASK_ID='classify_modems' AIRFLOW_CTX_EXECUTION_DATE='2025-05-30T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-30T10:00:00+00:00'
[2025-05-31T16:44:41.250-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-31T16:44:41.255-0600] {logging_mixin.py:190} INFO - üì• Loading modem and status data...
[2025-05-31T16:44:46.946-0600] {logging_mixin.py:190} INFO - ‚úÖ Loaded modem data: 1770208 rows from /tmp/modem_data.csv
[2025-05-31T16:44:46.947-0600] {logging_mixin.py:190} INFO - ‚úÖ Loaded status data: 477080 rows from /tmp/modem_status.csv
[2025-05-31T16:44:47.533-0600] {logging_mixin.py:190} INFO - üìä Unique CM_MACs in modem_df: 476288
[2025-05-31T16:44:47.712-0600] {logging_mixin.py:190} INFO - üìä Unique CM_MACs in status_df: 476505
[2025-05-31T16:44:47.713-0600] {logging_mixin.py:190} INFO - üßÆ Classifying each channel...
[2025-05-31T16:45:32.324-0600] {logging_mixin.py:190} INFO - ‚úÖ Channel classification complete.
[2025-05-31T16:45:32.418-0600] {logging_mixin.py:190} INFO -          CM_MAC       PTIME Channel_Status
0  384C90BD0EA2  2025-05-30           Good
1  A42249FC5C31  2025-05-30           Good
2  A42249FC5C31  2025-05-30           Good
3  A42249FC5C31  2025-05-30           Good
4  1835D146159B  2025-05-30           Good
[2025-05-31T16:45:32.443-0600] {logging_mixin.py:190} INFO - üìä Grouping and summarizing modem data...
[2025-05-31T16:56:14.824-0600] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-05-31T16:56:14.825-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-31T16:56:14.829-0600] {process_utils.py:132} INFO - Sending 15 to group 6768. PIDs of all processes in the group: [6768]
[2025-05-31T16:56:14.829-0600] {process_utils.py:87} INFO - Sending the signal 15 to group 6768
[2025-05-31T16:56:14.830-0600] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-31T16:56:14.857-0600] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
  File "/home/***/.local/lib/python3.12/site-packages/***/__main__.py", line 62, in main
    args.func(args)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 64, in wrapper
    providers_configuration_loaded(func)(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 237, in worker
    _run_command_with_daemon_option(
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 50, in _run_command_with_daemon_option
    run_command_with_daemon_option(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/daemon_utils.py", line 86, in run_command_with_daemon_option
    callback()
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 230, in run_celery_worker
    celery_app.worker_main(options)
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
  File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/celery/bin/base.py", line 135, in caller
    return f(ctx, *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
  File "/home/***/.local/lib/python3.12/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/home/***/.local/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/***/.local/lib/python3.12/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
  File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
  File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
  File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
  File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
  File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
  File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
  File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 651, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 139, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 171, in _execute_in_fork
    args.func(args)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/***/dags/health_score_lpr.py", line 155, in classify_modems
    grouped = modem_df.groupby(["CM_MAC", "PTIME"]).apply(summarize_group)
  File "/home/***/.local/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1770, in apply
    result = self._python_apply_general(f, self._selected_obj)
  File "/home/***/.local/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1819, in _python_apply_general
    values, mutated = self.grouper.apply_groupwise(f, data, self.axis)
  File "/home/***/.local/lib/python3.12/site-packages/pandas/core/groupby/ops.py", line 911, in apply_groupwise
    res = f(group)
  File "/opt/***/dags/health_score_lpr.py", line 150, in summarize_group
    "TX_MAX": group["TX_MAX"].max()
  File "/home/***/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3869, in __getitem__
    return self._get_item_cache(key)
  File "/home/***/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4415, in _get_item_cache
    res = self._ixs(loc, axis=1)
  File "/home/***/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3804, in _ixs
    result = self._box_col_values(col_mgr, i)
  File "/home/***/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4392, in _box_col_values
    obj = self._constructor_sliced_from_mgr(values, axes=values.axes)
  File "/home/***/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 657, in _constructor_sliced_from_mgr
    ser._name = None  # caller is responsible for setting real name
  File "/home/***/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6225, in __setattr__
    object.__setattr__(self, name, value)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-05-31T16:56:14.880-0600] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/health_score_lpr.py", line 155, in classify_modems
    grouped = modem_df.groupby(["CM_MAC", "PTIME"]).apply(summarize_group)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1770, in apply
    result = self._python_apply_general(f, self._selected_obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1819, in _python_apply_general
    values, mutated = self.grouper.apply_groupwise(f, data, self.axis)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/ops.py", line 911, in apply_groupwise
    res = f(group)
          ^^^^^^^^
  File "/opt/airflow/dags/health_score_lpr.py", line 150, in summarize_group
    "TX_MAX": group["TX_MAX"].max()
              ~~~~~^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3869, in __getitem__
    return self._get_item_cache(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4415, in _get_item_cache
    res = self._ixs(loc, axis=1)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3804, in _ixs
    result = self._box_col_values(col_mgr, i)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4392, in _box_col_values
    obj = self._constructor_sliced_from_mgr(values, axes=values.axes)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 657, in _constructor_sliced_from_mgr
    ser._name = None  # caller is responsible for setting real name
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6225, in __setattr__
    object.__setattr__(self, name, value)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-05-31T16:56:14.887-0600] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=libertyPr_health_score_1, task_id=classify_modems, run_id=scheduled__2025-05-30T10:00:00+00:00, execution_date=20250530T100000, start_date=20250531T224440, end_date=20250531T225614
[2025-05-31T16:56:14.899-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-31T16:56:14.900-0600] {standard_task_runner.py:124} ERROR - Failed to execute job 258 for task classify_modems ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(libertyPr_health_score_1, classify_modems, scheduled__2025-05-30T10:00:00+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'classify_modems', 'dag_id': 'libertyPr_health_score_1', 'run_id': 'scheduled__2025-05-30T10:00:00+00:00', 'map_index': -1, 'start_date': datetime.datetime(2025, 5, 31, 22, 44, 40, 930586, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 5, 31, 22, 56, 14, 886504, tzinfo=Timezone('UTC')), 'duration': 693}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 6768)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/health_score_lpr.py", line 155, in classify_modems
    grouped = modem_df.groupby(["CM_MAC", "PTIME"]).apply(summarize_group)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1770, in apply
    result = self._python_apply_general(f, self._selected_obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1819, in _python_apply_general
    values, mutated = self.grouper.apply_groupwise(f, data, self.axis)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/ops.py", line 911, in apply_groupwise
    res = f(group)
          ^^^^^^^^
  File "/opt/airflow/dags/health_score_lpr.py", line 150, in summarize_group
    "TX_MAX": group["TX_MAX"].max()
              ~~~~~^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3869, in __getitem__
    return self._get_item_cache(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4415, in _get_item_cache
    res = self._ixs(loc, axis=1)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3804, in _ixs
    result = self._box_col_values(col_mgr, i)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4392, in _box_col_values
    obj = self._constructor_sliced_from_mgr(values, axes=values.axes)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 657, in _constructor_sliced_from_mgr
    ser._name = None  # caller is responsible for setting real name
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6225, in __setattr__
    object.__setattr__(self, name, value)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ForeignKeyViolation: insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(libertyPr_health_score_1, classify_modems, scheduled__2025-05-30T10:00:00+00:00, -1) is not present in table "task_instance".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 328, in _run_raw_task
    ti.handle_failure(e, test_mode, context, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3434, in handle_failure
    _handle_failure(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1244, in _handle_failure
    TaskInstance.save_to_db(task_instance, session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3402, in save_to_db
    ti.get_dagrun().refresh_from_db()
    ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 96, in wrapper
    with create_session() as session:
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 57, in create_session
    session.commit()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1454, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 832, in commit
    self._prepare_impl()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 811, in _prepare_impl
    self.session.flush()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3588, in _flush
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(libertyPr_health_score_1, classify_modems, scheduled__2025-05-30T10:00:00+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'classify_modems', 'dag_id': 'libertyPr_health_score_1', 'run_id': 'scheduled__2025-05-30T10:00:00+00:00', 'map_index': -1, 'start_date': datetime.datetime(2025, 5, 31, 22, 44, 40, 930586, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 5, 31, 22, 56, 14, 886504, tzinfo=Timezone('UTC')), 'duration': 693}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2025-05-31T16:56:15.321-0600] {process_utils.py:80} INFO - Process psutil.Process(pid=6768, status='terminated', exitcode=1, started='16:44:40') (6768) terminated with exit code 1
[2025-05-31T17:15:21.623-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-31T17:15:21.670-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [queued]>
[2025-05-31T17:15:21.688-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [queued]>
[2025-05-31T17:15:21.688-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-31T17:15:21.711-0600] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): classify_modems> on 2025-05-30 10:00:00+00:00
[2025-05-31T17:15:21.724-0600] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=7153) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-31T17:15:21.727-0600] {standard_task_runner.py:72} INFO - Started process 7155 to run task
[2025-05-31T17:15:21.728-0600] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'libertyPr_health_score_1', 'classify_modems', 'scheduled__2025-05-30T10:00:00+00:00', '--job-id', '270', '--raw', '--subdir', 'DAGS_FOLDER/health_score_lpr.py', '--cfg-path', '/tmp/tmpxazn29ch']
[2025-05-31T17:15:21.732-0600] {standard_task_runner.py:105} INFO - Job 270: Subtask classify_modems
[2025-05-31T17:15:21.812-0600] {task_command.py:467} INFO - Running <TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [running]> on host 439130e6349d
[2025-05-31T17:15:21.966-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='libertyPr_health_score_1' AIRFLOW_CTX_TASK_ID='classify_modems' AIRFLOW_CTX_EXECUTION_DATE='2025-05-30T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-30T10:00:00+00:00'
[2025-05-31T17:15:21.969-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-31T17:15:21.974-0600] {logging_mixin.py:190} INFO - üì• Loading modem and status data...
[2025-05-31T17:15:27.444-0600] {logging_mixin.py:190} INFO - ‚úÖ Loaded modem data: 1770208 rows from /tmp/modem_data.csv
[2025-05-31T17:15:27.445-0600] {logging_mixin.py:190} INFO - ‚úÖ Loaded status data: 477080 rows from /tmp/modem_status.csv
[2025-05-31T17:15:27.990-0600] {logging_mixin.py:190} INFO - üìä Unique CM_MACs in modem_df: 476288
[2025-05-31T17:15:28.133-0600] {logging_mixin.py:190} INFO - üìä Unique CM_MACs in status_df: 476505
[2025-05-31T17:15:28.134-0600] {logging_mixin.py:190} INFO - üßÆ Classifying each channel...
[2025-05-31T17:16:19.435-0600] {logging_mixin.py:190} INFO - ‚úÖ Channel classification complete.
[2025-05-31T17:16:19.518-0600] {logging_mixin.py:190} INFO -          CM_MAC       PTIME Channel_Status
0  50A5DC706C6D  2025-05-30           Good
1  E45740B637B6  2025-05-30           Good
2  E45740B637B6  2025-05-30           Good
3  E45740B637B6  2025-05-30           Good
4  E45740B637B6  2025-05-30           Good
[2025-05-31T17:16:19.545-0600] {logging_mixin.py:190} INFO - üìä Grouping and summarizing modem data...
[2025-05-31T17:26:29.637-0600] {logging_mixin.py:190} INFO - ‚úÖ Grouped modem data shape: (476288, 4)
[2025-05-31T17:26:29.731-0600] {logging_mixin.py:190} INFO - ‚úÖ Summarized modem data (head):
[2025-05-31T17:26:29.758-0600] {logging_mixin.py:190} INFO -          CM_MAC       PTIME  ...              CHANNEL_NAME TX_MAX
0  00015C6CD846  2025-05-30  ...  cable-upstream 3/10/12.0    NaN
1  00071100F727  2025-05-30  ...    cable-upstream 2/6/7.0    NaN
2  000711146ABC  2025-05-30  ...   cable-upstream 4/7/14.0    NaN
3  00071117BB95  2025-05-30  ...    cable-upstream 4/4/0.0    NaN
4  00071117BBAE  2025-05-30  ...    cable-upstream 2/9/2.0    NaN

[5 rows x 6 columns]
[2025-05-31T17:26:29.759-0600] {logging_mixin.py:190} INFO - üîó Merging modem-level data with status (LEFT join)...
[2025-05-31T17:26:31.229-0600] {logging_mixin.py:190} INFO - ‚úÖ Merged dataset shape: (476363, 19)
[2025-05-31T17:26:31.231-0600] {logging_mixin.py:190} INFO - üìä Rows with no ONLINE_COUNT after merge: 0
[2025-05-31T17:26:31.231-0600] {logging_mixin.py:190} INFO - üõ† Applying final classification rules...
[2025-05-31T17:26:31.299-0600] {logging_mixin.py:190} INFO - üìä Classification summary after status logic:
[2025-05-31T17:26:31.310-0600] {logging_mixin.py:190} INFO - Category
Good        238617
Warning     138159
Critical     93506
Offline       6081
Name: count, dtype: int64
[2025-05-31T17:26:36.641-0600] {logging_mixin.py:190} INFO - üíæ Saved classified modems to /tmp/classified_modems.csv
[2025-05-31T17:26:36.642-0600] {logging_mixin.py:190} INFO - üîç Final modem count: 476363 rows
[2025-05-31T17:26:37.039-0600] {python.py:240} INFO - Done. Returned value was: None
[2025-05-31T17:26:37.061-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-31T17:26:37.062-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=libertyPr_health_score_1, task_id=classify_modems, run_id=scheduled__2025-05-30T10:00:00+00:00, execution_date=20250530T100000, start_date=20250531T231521, end_date=20250531T232637
[2025-05-31T17:26:37.230-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-31T17:26:37.293-0600] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-31T17:26:37.297-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-31T18:39:06.272-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-31T18:39:06.307-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [queued]>
[2025-05-31T18:39:06.320-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [queued]>
[2025-05-31T18:39:06.321-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-31T18:39:06.340-0600] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): classify_modems> on 2025-05-30 10:00:00+00:00
[2025-05-31T18:39:06.351-0600] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=8212) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-31T18:39:06.353-0600] {standard_task_runner.py:72} INFO - Started process 8214 to run task
[2025-05-31T18:39:06.354-0600] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'libertyPr_health_score_1', 'classify_modems', 'scheduled__2025-05-30T10:00:00+00:00', '--job-id', '286', '--raw', '--subdir', 'DAGS_FOLDER/health_score_lpr.py', '--cfg-path', '/tmp/tmpn70akjcc']
[2025-05-31T18:39:06.359-0600] {standard_task_runner.py:105} INFO - Job 286: Subtask classify_modems
[2025-05-31T18:39:06.435-0600] {task_command.py:467} INFO - Running <TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [running]> on host 439130e6349d
[2025-05-31T18:39:06.585-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='libertyPr_health_score_1' AIRFLOW_CTX_TASK_ID='classify_modems' AIRFLOW_CTX_EXECUTION_DATE='2025-05-30T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-30T10:00:00+00:00'
[2025-05-31T18:39:06.587-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-31T18:39:06.591-0600] {logging_mixin.py:190} INFO - üì• Loading modem and status data...
[2025-05-31T18:39:11.842-0600] {logging_mixin.py:190} INFO - ‚úÖ Loaded modem data: 1770208 rows from /tmp/modem_data.csv
[2025-05-31T18:39:11.843-0600] {logging_mixin.py:190} INFO - ‚úÖ Loaded status data: 477080 rows from /tmp/modem_status.csv
[2025-05-31T18:39:12.358-0600] {logging_mixin.py:190} INFO - üìä Unique CM_MACs in modem_df: 476288
[2025-05-31T18:39:12.486-0600] {logging_mixin.py:190} INFO - üìä Unique CM_MACs in status_df: 476505
[2025-05-31T18:39:12.487-0600] {logging_mixin.py:190} INFO - üßÆ Classifying each channel...
[2025-05-31T18:40:03.066-0600] {logging_mixin.py:190} INFO - ‚úÖ Channel classification complete.
[2025-05-31T18:40:03.169-0600] {logging_mixin.py:190} INFO -          CM_MAC       PTIME Channel_Status
0  1835D1B752EB  2025-05-30           Good
1  1835D1B73933  2025-05-30           Good
2  1835D1B752EB  2025-05-30           Good
3  1835D1B752EB  2025-05-30           Good
4  50A5DC213E54  2025-05-30           Good
[2025-05-31T18:40:03.198-0600] {logging_mixin.py:190} INFO - üìä Grouping and summarizing modem data...
[2025-05-31T18:50:25.726-0600] {logging_mixin.py:190} INFO - ‚úÖ Grouped modem data shape: (476288, 4)
[2025-05-31T18:50:25.809-0600] {logging_mixin.py:190} INFO - ‚úÖ Summarized modem data (head):
[2025-05-31T18:50:25.831-0600] {logging_mixin.py:190} INFO -          CM_MAC       PTIME  ...              CHANNEL_NAME TX_MAX
0  00015C6CD846  2025-05-30  ...  cable-upstream 3/10/12.0    NaN
1  00071100F727  2025-05-30  ...    cable-upstream 2/6/7.0    NaN
2  000711146ABC  2025-05-30  ...   cable-upstream 4/7/14.0    NaN
3  00071117BB95  2025-05-30  ...    cable-upstream 4/4/0.0    NaN
4  00071117BBAE  2025-05-30  ...    cable-upstream 2/9/2.0    NaN

[5 rows x 6 columns]
[2025-05-31T18:50:25.832-0600] {logging_mixin.py:190} INFO - üîó Merging modem-level data with status (LEFT join)...
[2025-05-31T18:50:27.040-0600] {logging_mixin.py:190} INFO - ‚úÖ Merged dataset shape: (476363, 19)
[2025-05-31T18:50:27.042-0600] {logging_mixin.py:190} INFO - üìä Rows with no ONLINE_COUNT after merge: 0
[2025-05-31T18:50:27.042-0600] {logging_mixin.py:190} INFO - üõ† Applying final classification rules...
[2025-05-31T18:50:27.090-0600] {logging_mixin.py:190} INFO - üìä Classification summary after status logic:
[2025-05-31T18:50:27.099-0600] {logging_mixin.py:190} INFO - Category
Good        238617
Warning     138159
Critical     93506
Offline       6081
Name: count, dtype: int64
[2025-05-31T18:50:32.190-0600] {logging_mixin.py:190} INFO - üíæ Saved classified modems to /tmp/classified_modems.csv
[2025-05-31T18:50:32.191-0600] {logging_mixin.py:190} INFO - üîç Final modem count: 476363 rows
[2025-05-31T18:50:32.520-0600] {python.py:240} INFO - Done. Returned value was: None
[2025-05-31T18:50:32.546-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-31T18:50:32.547-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=libertyPr_health_score_1, task_id=classify_modems, run_id=scheduled__2025-05-30T10:00:00+00:00, execution_date=20250530T100000, start_date=20250601T003906, end_date=20250601T005032
[2025-05-31T18:50:32.698-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-31T18:50:32.769-0600] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-31T18:50:32.772-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-31T23:17:18.864-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-31T23:17:18.907-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [queued]>
[2025-05-31T23:17:18.925-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [queued]>
[2025-05-31T23:17:18.925-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-31T23:17:18.954-0600] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): classify_modems> on 2025-05-30 10:00:00+00:00
[2025-05-31T23:17:18.969-0600] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=11916) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-31T23:17:18.972-0600] {standard_task_runner.py:72} INFO - Started process 11918 to run task
[2025-05-31T23:17:18.973-0600] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'libertyPr_health_score_1', 'classify_modems', 'scheduled__2025-05-30T10:00:00+00:00', '--job-id', '390', '--raw', '--subdir', 'DAGS_FOLDER/health_score_lpr.py', '--cfg-path', '/tmp/tmp7obvp74l']
[2025-05-31T23:17:18.977-0600] {standard_task_runner.py:105} INFO - Job 390: Subtask classify_modems
[2025-05-31T23:17:19.070-0600] {task_command.py:467} INFO - Running <TaskInstance: libertyPr_health_score_1.classify_modems scheduled__2025-05-30T10:00:00+00:00 [running]> on host 439130e6349d
[2025-05-31T23:17:19.233-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='libertyPr_health_score_1' AIRFLOW_CTX_TASK_ID='classify_modems' AIRFLOW_CTX_EXECUTION_DATE='2025-05-30T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-30T10:00:00+00:00'
[2025-05-31T23:17:19.237-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-31T23:17:19.242-0600] {logging_mixin.py:190} INFO - üì• Loading modem and status data...
[2025-05-31T23:17:24.909-0600] {logging_mixin.py:190} INFO - ‚úÖ Loaded modem data: 1770208 rows from /tmp/modem_data.csv
[2025-05-31T23:17:24.910-0600] {logging_mixin.py:190} INFO - ‚úÖ Loaded status data: 477080 rows from /tmp/modem_status.csv
[2025-05-31T23:17:25.397-0600] {logging_mixin.py:190} INFO - üìä Unique CM_MACs in modem_df: 476288
[2025-05-31T23:17:25.523-0600] {logging_mixin.py:190} INFO - üìä Unique CM_MACs in status_df: 476505
[2025-05-31T23:17:25.524-0600] {logging_mixin.py:190} INFO - üßÆ Classifying each channel...
[2025-05-31T23:18:10.579-0600] {logging_mixin.py:190} INFO - ‚úÖ Channel classification complete.
[2025-05-31T23:18:10.655-0600] {logging_mixin.py:190} INFO -          CM_MAC       PTIME Channel_Status
0  DCA633F2F325  2025-05-30           Good
1  DCA633F2F325  2025-05-30           Good
2  A42249FC6021  2025-05-30           Good
3  DCA633F2F325  2025-05-30           Good
4  DCA633F2F325  2025-05-30           Good
[2025-05-31T23:18:10.677-0600] {logging_mixin.py:190} INFO - üìä Grouping and summarizing modem data...
[2025-05-31T23:27:57.250-0600] {logging_mixin.py:190} INFO - ‚úÖ Grouped modem data shape: (476288, 4)
[2025-05-31T23:27:57.338-0600] {logging_mixin.py:190} INFO - ‚úÖ Summarized modem data (head):
[2025-05-31T23:27:57.358-0600] {logging_mixin.py:190} INFO -          CM_MAC       PTIME  ...              CHANNEL_NAME TX_MAX
0  00015C6CD846  2025-05-30  ...  cable-upstream 3/10/12.0    NaN
1  00071100F727  2025-05-30  ...    cable-upstream 2/6/7.0    NaN
2  000711146ABC  2025-05-30  ...   cable-upstream 4/7/14.0    NaN
3  00071117BB95  2025-05-30  ...    cable-upstream 4/4/0.0    NaN
4  00071117BBAE  2025-05-30  ...    cable-upstream 2/9/2.0    NaN

[5 rows x 6 columns]
[2025-05-31T23:27:57.359-0600] {logging_mixin.py:190} INFO - üîó Merging modem-level data with status (LEFT join)...
[2025-05-31T23:27:58.667-0600] {logging_mixin.py:190} INFO - ‚úÖ Merged dataset shape: (476363, 19)
[2025-05-31T23:27:58.669-0600] {logging_mixin.py:190} INFO - üìä Rows with no ONLINE_COUNT after merge: 0
[2025-05-31T23:27:58.669-0600] {logging_mixin.py:190} INFO - üõ† Applying final classification rules...
[2025-05-31T23:27:58.720-0600] {logging_mixin.py:190} INFO - üìä Classification summary after status logic:
[2025-05-31T23:27:58.728-0600] {logging_mixin.py:190} INFO - Category
Good        238617
Warning     138159
Critical     93506
Offline       6081
Name: count, dtype: int64
[2025-05-31T23:28:04.124-0600] {logging_mixin.py:190} INFO - üíæ Saved classified modems to /tmp/classified_modems.csv
[2025-05-31T23:28:04.125-0600] {logging_mixin.py:190} INFO - üîç Final modem count: 476363 rows
[2025-05-31T23:28:04.439-0600] {python.py:240} INFO - Done. Returned value was: None
[2025-05-31T23:28:04.468-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-31T23:28:04.469-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=libertyPr_health_score_1, task_id=classify_modems, run_id=scheduled__2025-05-30T10:00:00+00:00, execution_date=20250530T100000, start_date=20250601T051718, end_date=20250601T052804
[2025-05-31T23:28:04.623-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-31T23:28:04.688-0600] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-31T23:28:04.691-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
